### ISSUE TITLE
Unable to run the test-time training code

### ISSUE THREAD

**Issue by mihirp1998** [yossigandelsman/test_time_training_mae#6]
Hi,

I'm unable to get the TTT code running. Specifically when i run ur code main_test_time_training.py without any edits from my side , I get the following errors:
`
MAE pre-training: error: unrecognized arguments: --dataset_name imagenet_c`

I fixed the above error by removing dataset_name argument, but then however i get this error:
```

Traceback (most recent call last):
  File "main_test_time_training.py", line 230, in <module>
    main(args)
  File "main_test_time_training.py", line 145, in main
    misc.init_distributed_mode(args)
  File "/home/mprabhud/phd_projects/test_time_training_mae/util/misc.py", line 245, in init_distributed_mode
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/grogu/user/mprabhud/miniconda3/envs/ttt/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 627, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/grogu/user/mprabhud/miniconda3/envs/ttt/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 227, in _store_based_barrier
    store.add(store_key, 1)
RuntimeError: open(/): Is a directory
```

**Comment by mihirp1998** [comment]
fixed it by setting few environment variables:
export TIME=$(date +%s%3N)
OUTPUT_DIR_BASE= ABSOLUTE_PATH
